In [3]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [4]:
arr = np.array([1,2,3,4], ndmin=5)
print('dim:', arr.ndim)

dim: 5


In [8]:
arr = np.array([1,2,3,4,5])
print(arr[0]+arr[3])

5


In [24]:
c = np.array([[1,2,3],[4,5,6]])
print(c[0:2,1:4])


[[2 3]
 [5 6]]


In [15]:
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d[-1, -2, -2])

2


In [25]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:3])
print(arr.dtype)

[2 5]
int64


In [29]:
arr = np.array([1,2,3,4], dtype = 'i4')

print(arr.dtype)

int32


In [40]:
arr = np.array([1.1, 2.1, 3.1])
new = arr.astype(bool)
c = np.array2string(arr, seperator =',')

print(arr.dtype)
print(new)
print(c)

TypeError: array2string() got an unexpected keyword argument 'seperator'

In [41]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42 
print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [42]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [43]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [44]:
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d.shape)

(2, 2, 3)


In [45]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
import numpy as np
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d.reshape(4,3))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [3]:
#base= none--> copy 
#base= array-->view 
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new = arr.reshape(2,4)
print(new)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [7]:
arr = np.array([1,2,3])
for x in arr: 
    print(x)

1
2
3


In [9]:
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [14]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [13]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [15]:
#NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].
arr = np.array([1,2,3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [18]:
#enumeration --> sequence number of sometings one by one 
arr = np.array([[1,2,3,4], [5,6,7,8]])
for idx in np.ndenumerate(arr):
    print(idx)

((0, 0), np.int64(1))
((0, 1), np.int64(2))
((0, 2), np.int64(3))
((0, 3), np.int64(4))
((1, 0), np.int64(5))
((1, 1), np.int64(6))
((1, 2), np.int64(7))
((1, 3), np.int64(8))


In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [22]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1,arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [1]:
import numpy as np
arr = np.array([1,2,3])
#it doesn't change the datatype in place thus it needs more space and hence we use buffered
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [3]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[ ::2]):
  print(x)

1
2
3
4


In [7]:
#enumerate kya karta hai humein position deta hai cheezon ki 
arr = np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [8]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [10]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
# axis=0 concatenates--> horizontally while 1 verticlly

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
#new dimensions 
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 4)
print(newarr[0])

[1 2]


In [6]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)
#vertical concatenation into single array 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)
#this gives  u the index but 
print(x)

(array([0, 2, 4, 6]),)


In [21]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 4,  side='right')

print(x)

0


In [22]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)


[1 2 3]


In [23]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [24]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [26]:
arr = np.array([True, False , True ])

print(np.sort(arr))

[False  True  True]


In [27]:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [28]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [2]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = []
for e in arr:
    if e>42:
        filter_arr.append(True)
    

In [3]:
from numpy import random 
x = random.rand(3, 5)
print(x)


[[0.04164892 0.97899319 0.18675921 0.3942633  0.66913214]
 [0.16280399 0.30148806 0.27354315 0.39109457 0.33067486]
 [0.09951662 0.73562848 0.04094634 0.88592514 0.67415512]]


In [4]:
x = random.rand(4)
print(x)

[0.27487013 0.26726019 0.91591733 0.54156212]


In [6]:
x = random.choice([3, 5, 7, 9])
print(x)

5


In [7]:
x = random.choice([3, 5, 7, 9], size=(3,5))
print(x)

[[9 9 7 5 7]
 [3 9 3 3 3]
 [5 5 5 9 5]]


In [10]:
#data distribution--> plot karna 
#random distribution--> pdf- probablity density function--> continous probability 
#choice--> probabilities 
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3,2))
print(x)

[[7 5]
 [7 7]
 [7 5]]
